version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=
      - DATABASE_PORT=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=
      - DATABASE_USERNAME=
      - SECRET_KEY=
      - ALGORITHM=
      - ACCESS_TOKEN_EXPIRE_MINUTES=

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: